
#### mafiste to API GATEWAY
apiVersion: v1
kind: Secret
metadata:
  name: secret-api
  namespace: operator
type: Opaque
data:
  username: dGVzdA==
  password: dGVzdA==
  service_url: aHR0cDovL3NlcnZpY2UtbmV0d29yay1hcGkub3BlcmF0b3Iuc3ZjLmNsdXN0ZXIubG9jYWwvc2VydmljZS9wb3N0
  
---

apiVersion: v1
kind: Service
metadata:
    name: service-network-api
    namespace: operator
spec:
  selector:
    app: service-network-api
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

      

  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-api-test
  namespace: operator
  labels: 
    app: service-network-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-network-api
  template:
    metadata:
      labels:
        app: service-network-api
    spec:
      serviceAccountName: service-account-network-watcher-mock
      containers:
      - name: network-watcher-api
        image: smodou/network-watcher-api-mock:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: IN_CLUSTER 
          value: "true" 
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name




